---
- name: ProvisionEC2Box
  ec2:
    region: us-east-2 #"{{ ec2.region }}"
    keypair: puneet_aws #"{{ ec2.credentials }}"
    #instance_tags: "{{ ec2.tags }}"
    image: ami-0cd3dfa4e37921605 #"{{ ec2.image }}"
    instance_type: t2.micro #"{{ ec2.instance_type }}"
    #instance_profile_name: "{{ ec2.role | default('') }}"
    vpc_subnet_id: subnet-3f3c0857 #"{{ ec2.subnet }}"
    #assign_public_ip: "{{ ec2.public_ip | default('no') }}"
    #private_ip: "{{ ec2.private_ip | default('') }}"
    wait: true
    count: 1     
